from urllib.parse import parse_qs, urlparse

from elody.policies.helpers import get_flat_item_and_object_lists
from flask import g, request
from flask_restful import Headers
from inuits_policy_based_auth import RequestContext
from policy_factory import authenticate
from resources.base_resource import BaseResource
from resources.elody._blueprint import api
from resources.elody.document import ElodyDocument
from resources.elody.document_relations import ElodyDocumentRelations
from resources.elody.documents import ElodyDocuments
from resources.elody.filter import ElodyFilter
from werkzeug.exceptions import Conflict
from werkzeug.wrappers import Response


### DO NOT EDIT THIS FILE ###
class ElodyDocumentMediafiles(BaseResource):
    def __init__(self):
        super().__init__()
        self.document_relations_resource = ElodyDocumentRelations()
        self.document_resource = ElodyDocument()
        self.documents_resource = ElodyDocuments()
        self.filter_resource = ElodyFilter()

    @authenticate(RequestContext(request))
    def get(
        self,
        *,
        id,
        relations_stored_on_mediafile,
        flat_ref_mediafiles_key,
        **kwargs,
    ):
        document = self._check_if_collection_and_item_exists(None, id) or {}
        if relations_stored_on_mediafile:
            key = flat_ref_mediafiles_key
            value = document["identifiers"]
        else:
            flat_document, _ = get_flat_item_and_object_lists(document)
            key = "identifiers"
            value = flat_document.get(flat_ref_mediafiles_key) or []
            if not isinstance(value, list):
                value = [value]
        g.content = [
            {"type": "type", "value": "mediafile"},
            {"type": "selection", "key": key, "value": value, "match_exact": True},
        ]
        return self.filter_resource.post(**kwargs)

    def post(
        self,
        *,
        id,
        store_relations_on_mediafile,
        mediafile_relation_type,
        technical_origin_relation_type_template,
        **kwargs,
    ):
        # future: extend validation with an optional list of state validators like parsers
        # far future: validators bound to usecases => ocr_locked_validator validating ocr_locked no matter the entity type
        # pseudo code:
        #     from typing import Protocol, runtime_checkable

        #     @runtime_checkable
        #     class OCRLockedEntity(Protocol):
        #         ocr_locked: bool

        #     def validate_ocr_locked(entity: OCRLockedEntity) -> None:
        #         if entity.ocr_locked:
        #             raise ValueError("Cannot modify: entity is OCR locked.")

        original_headers = dict(request.headers)
        request.headers = Headers({**request.headers, "Accept": "application/json"})
        flat_document = self.__get_flat_document(id, **kwargs)
        if flat_document["type"] == "mediafile":
            for asset_ref in flat_document.get("ref_assets", []):
                flat_asset = self.__get_flat_document(asset_ref, **kwargs)
                if flat_asset.get("metadata.ocr_locked.value"):
                    raise Conflict("OCR is locked for this entity.")
        elif flat_document.get("metadata.ocr_locked.value"):
            raise Conflict("OCR is locked for this entity.")
        request.headers = Headers(original_headers)

        mediafile = g.get("content") or request.get_json()
        relation_metadata = mediafile.pop("relation_properties", {})
        mediafile = {**mediafile, "type": "mediafile"}
        get_relations = lambda key: [
            *(mediafile.get("relations", []) if key == id else []),
            {
                **relation_metadata,
                "key": key,
                "type": (
                    mediafile_relation_type
                    if mediafile.get("technical_origin", "original")
                    in ["original", "download"]
                    else technical_origin_relation_type_template.replace(
                        "TECHNICAL_ORIGIN",
                        mediafile["technical_origin"].title(),
                    )
                ),
            },
        ]

        if store_relations_on_mediafile:
            mediafile["relations"] = get_relations(id)

        g.content = mediafile
        response = self.documents_resource.post(**kwargs)
        if isinstance(response, tuple):
            return response

        if not store_relations_on_mediafile:
            mediafile_id = (
                parse_qs(urlparse(response).query)["id"][0]
                if isinstance(response, str)
                else response["_id"]
            )
            g.content = get_relations(mediafile_id)
            self.document_relations_resource.post(id=id, **kwargs)

        return response, 201

    def __get_flat_document(self, id, **kwargs):
        document = self.document_resource.get(id=id, **kwargs)
        if isinstance(document, Response):
            document = document.json
        flat_document, _ = get_flat_item_and_object_lists(document)
        return flat_document


def resource_rules():
    return [
        {
            "route": "/entities/<string:id>/mediafiles",
            "resource": ElodyDocumentMediafiles,
            "api": api,
        },
    ]
