from flask import g
from resources.base_resource import BaseResource
from resources.elody._blueprint import api
from resources.elody.document import ElodyDocument


### DO NOT EDIT THIS FILE ###
class ElodyDocumentPrimaryThumbnail(BaseResource):
    def __init__(self):
        super().__init__()
        self.resource = ElodyDocument()

    def put(self, mediafile_id, **kwargs):
        g.content = {"primary_thumbnail_id": mediafile_id}
        self.resource.patch(**kwargs)
        return "", 204


def resource_rules():
    return [
        {
            "route": "/entities/<string:id>/set_primary_thumbnail/<string:mediafile_id>",
            "resource": ElodyDocumentPrimaryThumbnail,
            "api": api,
        }
    ]
