import os
import re
from mimetypes import guess_type
from urllib.parse import parse_qs, urlparse

from cloudevents.conversion import to_dict
from cloudevents.http import CloudEvent
from configuration import get_object_configuration_mapper
from flask import Response, request
from inuits_policy_based_auth import RequestContext
from policy_factory import apply_policies, get_user_context
from rabbit import get_rabbit
from resources.base_resource import BaseResource
from resources.elody._blueprint import api
from resources.elody.mediafiles.mediafile import ElodyMediafile

ROUTING_KEY_PREFIX = os.getenv("ROUTING_KEY_PREFIX", "dams")


### DO NOT EDIT THIS FILE ###
class ElodyMediafileGenerateTranscode(BaseResource):
    NOT_TRANSCODABLE_MIMETYPES = [
        "application/pdf",
        "application/xml",
        "text/plain",
        "text/xml",
    ]

    def __init__(self):
        super().__init__()
        self.resource = ElodyMediafile()
        job_config = get_object_configuration_mapper().get("job")
        self.__start_job = job_config.crud()["start_job"]
        self.__init_job = job_config.crud()["init_job"]
        self.__warn_job = job_config.crud()["finish_job_with_warning"]

    @apply_policies(RequestContext(request))
    def patch(self, id, **kwargs):
        if request.args.get("soft", 0, int):
            return "good", 200

        parent_job_id = kwargs.pop("parent_job_id", None)

        entity = self.resource.get(id=id, **kwargs)
        if isinstance(entity, Response):
            entity = entity.json

        generate_transcode_job_id = self.__init_job(
            f"{f'Generate transcode for {entity["type"]} | {id}' if id else f'Generate transcode | missing entity | {id}'}",  # noqa
            "Generate Transcode",
            get_rabbit=lambda: get_rabbit(),
            user_email=get_user_context().email,
            parent_id=parent_job_id,
            track_async_children=True,
        )

        self.__start_job(
            generate_transcode_job_id,
            get_rabbit=lambda: get_rabbit(),
        )
        technical_origin = entity["technical_origin"]
        if technical_origin != "original":
            # If it's not an original file the transcode should not be re-generated
            self.__warn_job(
                generate_transcode_job_id,
                info_message="Mediafile is not original",
                get_rabbit=get_rabbit,
            )
            # TODO: return code
            return 200

        # TODO: should this get the download_urls from the download-urls endpoint?
        download_url = urlparse(entity["original_file_location"])
        ticket_id = parse_qs(download_url.query)["ticket_id"]
        ticket = self.storage.get_item_from_collection_by_id(
            collection="abstracts",
            id=ticket_id,
        )
        mimetype = entity["mimetype"]
        if not mimetype:
            mimetype = guess_type(entity["original_filename"])
        url = (
            f"{re.sub(r'/storage/v1/?$', '', self.storage_api_url)}{download_url.path}?{download_url.query}",  # noqa
        )
        headers = {"Authorization": f"Bearer {os.getenv('STATIC_JWT')}"}
        self.__send_transcode_generation_message(
            mediafile=entity,
            mimetype=mimetype,
            url=url,
            headers=headers,
            ticket=ticket,
            parent_job_id=generate_transcode_job_id,
        )

        response = 200
        return self._create_response_according_accept_header(response)

    def __send_transcode_generation_message(
        self,
        mediafile,
        mimetype,
        url,
        headers,
        ticket=None,
        parent_job_id=None,
    ):
        attributes = {
            "type": "dams.regenerate_transcode",
            "source": "collection-api.regenerate_transcode",
        }
        data = {
            "mediafile": mediafile,
            "mimetype": mimetype,
            "url": url,
            "headers": headers,
            "ticket": ticket,
            "parent_job_id": parent_job_id,
            "ignore_duplicates": True,
        }
        cleaned_mimetype = mimetype.split(";")[0].strip().replace("/", ".")
        event = to_dict(CloudEvent(attributes, data))
        get_rabbit().send(
            event,
            routing_key=f"{ROUTING_KEY_PREFIX}.file_uploaded.{cleaned_mimetype}",
        )


def resource_rules():
    return [
        {
            "route": "/mediafiles/<string:id>/generate-transcode",
            "resource": ElodyMediafileGenerateTranscode,
            "api": api,
        },
    ]
