from resources.elody._blueprint import api
from resources.elody.filter import ElodyFilter


### DO NOT EDIT THIS FILE ###
class ElodyMediafileFilter(ElodyFilter):
    pass


def resource_rules():
    return [
        {"route": "/mediafiles/filter", "resource": ElodyMediafileFilter, "api": api}
    ]
