from configuration import get_object_configuration_mapper
from resources.base_resource import BaseResource
from resources.elody._blueprint import api
from resources.elody.mediafiles.mediafile import ElodyMediafile


### DO NOT EDIT THIS FILE ###
class ElodyMediafileDownloadUrls(BaseResource):
    def __init__(self):
        super().__init__()
        self.resource = ElodyMediafile()

    def get(self, **kwargs):
        mediafile = self.resource.get(**kwargs)
        config = get_object_configuration_mapper().get("mediafile")
        serialize = config.serialization(config.SCHEMA_TYPE, "texturilist")
        response = {}
        if url := serialize(mediafile):
            response.update({"original_file_location": url})
        if url := serialize(mediafile, filename_key="display_filename"):
            response.update({"transcode_file_location": url})
        return response, 200


def resource_rules():
    return [
        {
            "route": "/mediafiles/<string:id>/download-urls",
            "resource": ElodyMediafileDownloadUrls,
            "api": api,
        }
    ]
