from configuration import get_object_configuration_mapper
from flask import request
from inuits_policy_based_auth import RequestContext
from policy_factory import apply_policies, get_user_context
from rabbit import get_rabbit
from resources.base_resource import BaseResource
from resources.elody._blueprint import api
from resources.elody.mediafiles.mediafile_generate_transcode import (
    ElodyMediafileGenerateTranscode,
)
from urllib.parse import urlparse, parse_qs
from mimetypes import guess_type
from cloudevents.conversion import to_dict
from cloudevents.http import CloudEvent
import re
import os


### DO NOT EDIT THIS FILE ###
class ElodyMediafilesGenerateTranscode(BaseResource):
    NOT_TRANSCODABLE_MIMETYPES = [
        "application/pdf",
        "application/xml",
        "audio/mpeg",
        "image/jpeg",
        "text/plain",
        "text/xml",
        "video/mp4",
    ]

    def __init__(self):
        super().__init__()
        self.resource = ElodyMediafileGenerateTranscode()
        job_config = get_object_configuration_mapper().get("job")
        self.__start_job = job_config.crud()["start_job"]
        self.__init_job = job_config.crud()["init_job"]
        self.__warn_job = job_config.crud()["finish_job_with_warning"]

    def post(self, **kwargs):
        if request.args.get("soft", 0, int):
            return "good", 200

        request.view_args = request.view_args or {}
        identifiers = request.get_json()["identifiers"]
        if not identifiers:
            return 400

        parent_generate_transcode_job_id = self.__init_job(
            f"Generate Transcodes for {identifiers}",
            "Bulk Transcode Generation",
            get_rabbit=lambda: get_rabbit(),
            user_email="developers@inuits.eu",
            # user_email=get_user_context().email,
            track_async_children=True,
        )

        self.__start_job(parent_generate_transcode_job_id, get_rabbit=get_rabbit)

        for id in identifiers:
            self.__set_request(id, "PATCH")
            self.resource.patch(
                id=id, parent_job_id=parent_generate_transcode_job_id, **kwargs
            )
        response = {"parent_job_id": parent_generate_transcode_job_id}
        return self._create_response_according_accept_header(response)

    def __set_request(self, id, method):
        request.method = method
        request.path = f"/mediafiles/{id}"
        request.view_args = {**(request.view_args or {}), "id": id}


def resource_rules():
    return [
        {
            "route": "/mediafiles/admin/generate-transcodes-bulk",
            "resource": ElodyMediafilesGenerateTranscode,
            "api": api,
        }
    ]
