from configuration import get_object_configuration_mapper
from flask import request
from inuits_policy_based_auth import RequestContext
from policy_factory import apply_policies, get_user_context
from resources.base_resource import BaseResource
from resources.elody._blueprint import api
from resources.elody.mediafiles.mediafile import ElodyMediafile


### DO NOT EDIT THIS FILE ###
class ElodyMediafileDownloadUrls(BaseResource):
    NOT_TRANSCODABLE_MIMETYPES = [
        "application/pdf",
        "application/xml",
        "audio/mpeg",
        "image/jpeg",
        "text/plain",
        "text/xml",
        "video/mp4",
    ]

    def __init__(self):
        super().__init__()
        self.resource = ElodyMediafile()

    @apply_policies(RequestContext(request))
    def get(self, **kwargs):
        copyright_access = get_user_context().bag["copyright_access"]
        mediafile = self.resource.get(**kwargs)
        if not isinstance(mediafile, dict):
            return mediafile

        config = get_object_configuration_mapper().get("mediafile")
        serialize = config.serialization(config.SCHEMA_TYPE, "texturilist")
        # NOTE: Using config.SCHEMA_TYPE is technically incorrect: The
        # ElodyMediafile will fetch mediafiles in the "elody" format. However,
        # the clients will try to serialize from their own formats in this
        # function. It doesn't matter particularly much for AICAP and DAMS it
        # looks like, but this broke for vliz However, the following fix won't
        # work for them since they don't have elody_to_texturilist functions,
        # but we should pick this back up at some point, in case a client goes
        # completely different in their mediafiles
        # serialize = config.serialization(
        #     mediafile.get("schema", {}).get("type", "elody"), "texturilist"
        # )
        response = {}

        if original_file_location := serialize(
            mediafile, copyright_access=copyright_access
        ):
            response.update({"original_file_location": original_file_location})
        if transcode_file_location := serialize(
            mediafile,
            filename_key="display_filename",
            copyright_access=copyright_access,
        ):
            response.update({"transcode_file_location": transcode_file_location})
        elif mediafile.get("mimetype") in self.NOT_TRANSCODABLE_MIMETYPES:
            response.update({"transcode_file_location": original_file_location})

        return response, 200


def resource_rules():
    return [
        {
            "route": "/mediafiles/<string:id>/download-urls",
            "resource": ElodyMediafileDownloadUrls,
            "api": api,
        }
    ]
