from flask import request
from inuits_policy_based_auth import RequestContext
from policy_factory import apply_policies, get_user_context
from resources.base_resource import BaseResource
from resources.elody._blueprint import api


### DO NOT EDIT THIS FILE ###
class ElodyMediafileCopyright(BaseResource):
    @apply_policies(RequestContext(request))
    def get(self, **_):
        return get_user_context().bag["copyright_access"], 200


def resource_rules():
    return [
        {
            "route": "/mediafiles/<string:id>/copyright",
            "resource": ElodyMediafileCopyright,
            "api": api,
        }
    ]
