from resources.elody._blueprint import api
from resources.elody.document import ElodyDocument


### DO NOT EDIT THIS FILE ###
class ElodyMediafile(ElodyDocument):
    pass


def resource_rules():
    return [
        {"route": "/mediafiles/<string:id>", "resource": ElodyMediafile, "api": api}
    ]
