from configuration import get_object_configuration_mapper
from resources.elody._blueprint import api
from resources.elody.documents import ElodyDocuments


### DO NOT EDIT THIS FILE ###
class ElodyMediafiles(ElodyDocuments):
    def get(self, **kwargs):
        config = get_object_configuration_mapper().get("mediafile")
        return super().get(collection=config.crud()["collection"], **kwargs)


def resource_rules():
    return [{"route": "/mediafiles", "resource": ElodyMediafiles, "api": api}]
