from resources.base_resource import BaseResource
from resources.elody._blueprint import api
from resources.elody.mediafiles.document_mediafiles import ElodyDocumentMediafiles


### DO NOT EDIT THIS FILE ###
class ElodyMediafileDerivatives(BaseResource):
    def __init__(self):
        super().__init__()
        self.resource = ElodyDocumentMediafiles()

    def post(self, **kwargs):
        return self.resource.post(**kwargs)


def resource_rules():
    return [
        {
            "route": "/mediafiles/<string:id>/derivatives",
            "resource": ElodyMediafileDerivatives,
            "api": api,
        }
    ]
