from configuration import get_object_configuration_mapper
from flask import request
from resources.elody._blueprint import api
from resources.elody.documents import ElodyDocuments
from werkzeug.datastructures import ImmutableMultiDict


### DO NOT EDIT THIS FILE ###
class ElodyMediafiles(ElodyDocuments):
    def get(self, **kwargs):
        request.args = ImmutableMultiDict(
            {**request.args, "type": "mediafile"}
        )  # pyright: ignore
        config = get_object_configuration_mapper().get("mediafile")
        return super().get(collection=config.crud()["collection"], **kwargs)


def resource_rules():
    return [{"route": "/mediafiles", "resource": ElodyMediafiles, "api": api}]
