---
###############################################################################
# PYTHON APPLICATION PIPELINE
###############################################################################

include:
  - project: 'inuits/gitlab-ci/pipeline-templates'
    ref: 'v2.2.2'
    file: 
      - '/pipelines/multi-customer-delivery.yml'
      - '/jobs/build-variant/pip.yml'

variables:
  PROJECT: 'dams'
  APPLICATION: 'dams-collection'

customer:
  parallel:
    matrix:
      - CUSTOMER: []
