---

# --------------------------------------------------------------
# Includes
# --------------------------------------------------------------
include:
  - project: 'inuits/gitlab-ci/pipeline-templates'
    file: 'pipelines/docker-build-no-uat.yml'
    ref: 'v4.0.0'


# --------------------------------------------------------------
# Variables
# --------------------------------------------------------------
variables:
  CUSTOMER: inuits
  PROJECT: dams
  APPLICATION: collection

  HARBOR_PROJECT_DEV: elody-dams-dev


# --------------------------------------------------------------
# Template overrides
# --------------------------------------------------------------

# Disable prod, not needed
deliver-prod:
  rules:
    - when: never
