---

# --------------------------------------------------------------
# Includes
# --------------------------------------------------------------
include:
  - project: 'inuits/gitlab-ci/pipeline-templates'
    ref: 'v4.2.0'
    file: 
      - 'pipelines/customers/deploy.yml'
      - 'jobs/docker/build-pip.yml'


# --------------------------------------------------------------
# Variables
# --------------------------------------------------------------
variables:
  CUSTOMER: inuits
  PROJECT: dams
  APPLICATION: collection

  SKIP_DEPLOY: 'true'

  HARBOR_PROJECT_DEV: elody-dams-dev
  TARGET_CLUSTER_DEV: inuits-prod


# --------------------------------------------------------------
# Template overrides
# --------------------------------------------------------------

# Only run pipeline for default branch
rules:
  - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    when: always
  - when: never

# Disable uat, not needed
uat:
  rules:
    - when: never

# Disable prod, not needed
prod:
  rules:
    - when: never
