from typing import Any

from object_configurations.object_configuration_mapper import ObjectConfigurationMapper
from storage.genericstore import GenericStorageManager

def init_mappers() -> None: ...
def get_object_configuration_mapper() -> ObjectConfigurationMapper: ...
def get_route_mapper() -> dict[str, str]: ...
def get_collection_mapper() -> dict[str, str]: ...
def get_storage_mapper() -> dict[str, type[GenericStorageManager]]: ...
def get_features() -> dict[str, dict[str, Any]]: ...
