from configuration import get_features
from resources.base.batch import Batch
from resources.base_resource import BaseResource
from resources.elody._blueprint import api

bulk_operation_features = get_features().get("bulk_operations", {}).keys()


### DO NOT EDIT THIS FILE ###
class ElodyBatch(BaseResource):
    def __init__(self):
        super().__init__()
        self.resource = Batch()

    def post(self, **kwargs):
        return self.resource.post(**kwargs)


def resource_rules():
    rules = []
    if "import" in bulk_operation_features:
        rules.append({"route": "/batch", "resource": ElodyBatch, "api": api})
    return rules
