from flask import g, request
from resources.base.document import Document
from resources.base_resource import BaseResource
from resources.elody._blueprint import api


### DO NOT EDIT THIS FILE ###
class ElodyDocumentMetadata(BaseResource):
    def __init__(self):
        super().__init__()
        self.resource = Document()

    def patch(self, **kwargs):
        g.content = {"metadata": request.get_json()}
        response = self.resource.patch(**kwargs)
        if isinstance(response, tuple):
            return response
        return response[0].get("metadata", [])


def resource_rules():
    return [
        {
            "route": "/elody/v1/entities/<string:id>/metadata",
            "resource": ElodyDocumentMetadata,
            "api": api,
        },
        {
            "route": "/entities/<string:id>/metadata",
            "resource": ElodyDocumentMetadata,
            "api": api,
        },
    ]
