from resources.base.document import Document
from resources.base_resource import BaseResource
from resources.elody._blueprint import api


### DO NOT EDIT THIS FILE ###
class ElodyDocument(BaseResource):
    def __init__(self):
        super().__init__()
        self.resource = Document()

    def get(self, **kwargs):
        return self.resource.get(**kwargs)

    def put(self, **kwargs):
        return self.resource.put(**kwargs)

    def patch(self, **kwargs):
        return self.resource.patch(**kwargs)

    def delete(self, **kwargs):
        return self.resource.delete(**kwargs)


def resource_rules():
    return [
        {
            "route": "/elody/v1/entities/<string:id>",
            "resource": ElodyDocument,
            "api": api,
        },
        {"route": "/entities/<string:id>", "resource": ElodyDocument, "api": api},
    ]
