from serialization.serialize import serialize
from policy_factory import authenticate
from inuits_policy_based_auth import RequestContext
from flask import g, request
from resources.base.document import Document
from resources.base_resource import BaseResource
from resources.elody._blueprint import api


### DO NOT EDIT THIS FILE ###
class ElodyDocumentRelations(BaseResource):
    def __init__(self):
        super().__init__()
        self.resource = Document()

    @authenticate(RequestContext(request))
    def post(self, id, spec):
        g.content = g.get("content") or request.get_json()
        document = self._check_if_collection_and_item_exists(None, id)
        document = serialize(document, type=document.get("type"), to_format=spec)
        g.content = g.get("content", []) + [
            document_relation
            for document_relation in document.get("relations", [])
            if not any(
                [
                    content_relation
                    for content_relation in g.get("content", [])
                    if document_relation["key"] == content_relation["key"]
                    and document_relation["type"] == content_relation["type"]
                ]
            )
        ]
        return self.put(id=id, spec=spec, document=document)

    @authenticate(RequestContext(request))
    def put(self, id, spec, document=None):
        g.content = g.get("content") or request.get_json()
        if not document:
            document = self._check_if_collection_and_item_exists(None, id)
            document = serialize(document, type=document.get("type"), to_format=spec)
        document["relations"] = [
            {**content, "sort": {}} if content.get("sort") is None else content
            for content in g.get("content", [])
        ]
        g.content = document
        response = self.resource.put(id=id, spec=spec)
        if isinstance(response, tuple):
            return response
        return response[0].get("relations", [])


def resource_rules():
    return [
        {
            "route": "/entities/<string:id>/relations",
            "resource": ElodyDocumentRelations,
            "api": api,
        }
    ]
