from configuration import get_features
from resources.base.documents import Documents
from resources.base_resource import BaseResource
from resources.elody._blueprint import api

bulk_operation_features = get_features().get("bulk_operations", {}).keys()


### DO NOT EDIT THIS FILE ###
class ElodyDocuments(BaseResource):
    def __init__(self):
        super().__init__()
        self.resource = Documents()

    def get(self, **kwargs):
        return self.resource.get(**kwargs)

    def post(self, **kwargs):
        return self.resource.post(**kwargs)

    def put(self, **kwargs):
        return self.resource.put(**kwargs)

    def delete(self, **kwargs):
        return self.resource.delete(**kwargs)


def resource_rules():
    if "edit" not in bulk_operation_features:
        ElodyDocuments.methods.discard("PUT")  # pyright: ignore
    return [{"route": "/entities", "resource": ElodyDocuments, "api": api}]
