from resources.base.filter import Filter
from resources.base_resource import BaseResource
from resources.elody._blueprint import api


### DO NOT EDIT THIS FILE ###
class ElodyFilter(BaseResource):
    def __init__(self):
        super().__init__()
        self.resource = Filter()

    def post(self, **kwargs):
        return self.resource.post(**kwargs)


def resource_rules():
    return [{"route": "/entities/filter", "resource": ElodyFilter, "api": api}]
