from configuration import get_object_configuration_mapper
from elody.job import fail_job, finish_job, init_job, start_job
from flask import g, request
from flask_restful import Headers
from inuits_policy_based_auth import RequestContext
from policy_factory import authenticate, get_user_context
from rabbit import get_rabbit
from requests.exceptions import HTTPError
from resources.base.document import Document
from resources.base.documents import Documents
from resources.base_resource import BaseResource
from serialization.serialize import serialize
from util import encode_content_type_header
from werkzeug.exceptions import (
    BadGateway,
    BadRequest,
    Forbidden,
    NotFound,
    Unauthorized,
)


### DO NOT EDIT THIS FILE AND DO NOT USE DIRECTLY ###
### contact @eray for more info or feature/bug reports; refs #146921 ###
class Batch(BaseResource):
    @authenticate(RequestContext(request))
    def post(self, *, spec, force_patch_only=False, **_):
        self.__set_request("POST")
        g.enable_parsers = True
        status_code = 201 if not force_patch_only else 200
        documents, errors, mediafile_errors, warnings = [], [], [], []
        line_count, content = 1, {}
        self.job_id = ""
        self.parent_job_id = None
        document_type = request.args.get("type", "")
        view_args_id = (request.view_args or {}).get("id")

        content_type = encode_content_type_header(request.content_type)
        has_accept_text_uri_list_header = (
            request.headers.get("Accept") == "text/uri-list"
        )
        request.headers = Headers(
            {
                **request.headers,
                "Content-Type": "application/json",
                "Accept": "application/json",
            },
        )

        try:
            default_config = get_object_configuration_mapper().get("_default")
            serialize_batch = default_config.serialization(
                content_type,
                default_config.SCHEMA_TYPE,
            )
            if not g.get("dry_run"):
                self.parent_job_id = request.args.get("parent_job_id", "")
                g.parent_job_id = self.parent_job_id
                self.job_id = init_job(
                    f"Import {request.args.get('filename', document_type.replace('_', ' ') if document_type else 'file')}",  # noqa
                    "Data Import",
                    get_rabbit=get_rabbit,
                    user_email=get_user_context().email,
                    parent_id=self.parent_job_id,
                    track_async_children=True,
                )
                start_job(self.job_id, get_rabbit=get_rabbit)
                g.current_job_id = self.job_id

            documents_resource = Documents()
            document_resource = Document()
            for content in serialize_batch(
                request.get_data(),
                document_type=document_type,
                request_args=request.args.to_dict(),
            ):
                line_count += 1
                contents = []
                for content in [content, *g.get("parsed_contents", [])]:
                    try:
                        if isinstance(content, Exception):
                            raise content
                        if not force_patch_only:
                            prepare_creation = (
                                get_object_configuration_mapper()
                                .get(content.get("type"))
                                .crud()["creation_preparer"]
                            )
                            content = prepare_creation(content)
                    except Exception as exception:
                        if isinstance(content, Exception):
                            errors, status_code = self.__process_errors(
                                errors,
                                exception,
                                status_code,
                                line_count=line_count,
                                document_type=document_type,
                            )
                        elif content.get("type") != "mediafile" or g.get("dry_run"):
                            errors, status_code = self.__process_errors(
                                errors,
                                exception,
                                status_code,
                                line_count=line_count,
                                document_type=content.get("type"),
                            )
                        else:
                            mediafile_errors, status_code = self.__process_errors(
                                mediafile_errors,
                                exception,
                                status_code,
                                line_count=line_count,
                                document_type="mediafile",
                            )
                    finally:
                        if isinstance(content, list):
                            contents.extend(content)
                        else:
                            contents.append(content)

                for content in contents:
                    try:
                        if isinstance(content, Exception):
                            raise content
                        if exceptions := content.get("exceptions"):
                            for exception in exceptions:
                                if content.get("type") != "mediafile" or g.get(
                                    "dry_run",
                                ):
                                    errors, status_code = self.__process_errors(
                                        errors,
                                        exception,
                                        status_code,
                                        line_count=line_count,
                                        document_type=content.get("type"),
                                    )
                                else:
                                    mediafile_errors, status_code = (
                                        self.__process_errors(
                                            mediafile_errors,
                                            exception,
                                            status_code,
                                            line_count=line_count,
                                            document_type=content.get("type"),
                                        )
                                    )
                            continue
                        document_type = content.get("type")
                        g.content = content

                        if force_patch_only or any(
                            set(content["identifiers"]) & set(document["identifiers"])
                            for document in documents
                        ):
                            if not g.get("dry_run"):
                                id = content.pop("identifiers")[0]
                                g.content = serialize(
                                    content,
                                    type=content.get("type"),
                                    to_format=spec,
                                )
                                try:
                                    response = document_resource.patch(id=id, spec=spec)
                                except NotFound as exception:
                                    if not force_patch_only:
                                        raise exception
                                    response = None
                            else:
                                response = None
                        else:
                            response = documents_resource.post(
                                spec=spec,
                                is_content_prepared_for_creation=True,
                            )

                        if response is None:
                            continue
                        if isinstance(response, tuple):
                            if response[1] >= 500:
                                raise Exception(response[0])
                            elif response[1] >= 400:
                                try:
                                    message = response[0]["message"]
                                except Exception:
                                    message = str(response[0])
                                if response[1] == 409:
                                    warnings, _ = self.__process_errors(
                                        warnings,
                                        message,
                                        status_code,
                                        line_count=line_count,
                                        document_type=document_type,
                                    )
                                else:
                                    raise BadRequest(message)
                            elif response[1] == 200 and request.method == "PATCH":
                                documents = [
                                    document
                                    for document in documents
                                    if document["_id"] != response[0]["_id"]
                                ]
                                documents.append(response[0])
                        else:
                            documents.append(response)
                    except Exception as exception:
                        if g.get("content", {}).get("type") != "mediafile" or g.get(
                            "dry_run",
                        ):
                            errors, status_code = self.__process_errors(
                                errors,
                                exception,
                                status_code,
                                line_count=line_count,
                                document_type=document_type,
                            )
                        else:
                            mediafile_errors, status_code = self.__process_errors(
                                mediafile_errors,
                                exception,
                                status_code,
                                line_count=line_count,
                                document_type="mediafile",
                            )
                    finally:
                        if request.args.get("soft"):
                            break
                g.parsed_contents = []
            if not content:
                raise BadRequest("File has no content")
        except BadRequest as exception:
            errors, status_code = self.__process_errors(
                errors,
                exception,
                status_code,
                line_count=line_count,
                document_type=document_type,
            )
        except Exception as exception:
            errors, status_code = self.__process_errors(
                errors,
                exception,
                status_code,
                line_count=line_count,
                document_type=document_type,
            )
        finally:
            if view_args_id:
                request.view_args = {"id": view_args_id}
            if not g.get("dry_run"):
                if len(errors) == 0:
                    finish_job(self.job_id, get_rabbit=get_rabbit)
                else:
                    fail_job(self.job_id, "\n".join(errors), get_rabbit=get_rabbit)
            if status_code == 500:
                output = {}
                output.update(
                    {
                        "errors": {
                            "entities": errors,
                            "mediafiles": mediafile_errors,
                        },
                    },
                )
                if not g.get("dry_run"):
                    output.update({"job_id": self.job_id})
                return output, status_code
            if has_accept_text_uri_list_header:
                return "\n".join(self.__format_text_uri_list()), status_code
            return {
                "entities": [
                    document
                    for document in documents
                    if document["type"] != "mediafile"
                ],
                "mediafiles": [
                    document
                    for document in documents
                    if document["type"] == "mediafile"
                ],
                "links": self.__format_text_uri_list(),
                "warnings": {
                    "entities": warnings,
                    "mediafiles": [],
                },
                "errors": {
                    "entities": errors,
                    "mediafiles": mediafile_errors,
                },
                "job_id": self.job_id,
                "parent_job_id": self.parent_job_id,
            }, status_code

    def __process_errors(
        self,
        errors,
        exception,
        status_code,
        *,
        line_count=None,
        document_type="",
    ):
        if isinstance(exception, HTTPError):
            try:
                message = exception.response.json()["message"]
            except:
                message = exception.response.text
            message = message.replace('"', "").replace("'", "")
        elif isinstance(exception, (BadGateway, BadRequest, Unauthorized, Forbidden)):
            config = get_object_configuration_mapper().get(document_type)
            construct_document_exception_message = config.crud()[
                "document_exception_message_constructor"
            ]
            message = construct_document_exception_message(
                exception,
                str(exception.description),
            )
        elif isinstance(exception, NotFound):
            message = (
                f"Could not create {document_type} due to failed creation of parent"
            )
        elif isinstance(exception, str):
            message = exception
        else:
            message = repr(exception)
        message = f"{message}{f' | {document_type}' if document_type else ''}"

        if message.find("W2003") == -1:
            if line_count is not None:
                line_info = f"{line_count})"
                message = f"{line_info} {message}"
                message = message.replace("| prefix:", f"| prefix:{line_info}")
            if message not in errors:
                errors.append(message)
        else:
            return errors, status_code

        if isinstance(exception, HTTPError):
            status_code = exception.response.status_code
        elif isinstance(exception, BadRequest):
            status_code = 400
        elif isinstance(exception, Unauthorized):
            status_code = 401
        elif isinstance(exception, Forbidden):
            status_code = 403
        else:
            status_code = 500 if status_code < 400 else status_code

        return errors, status_code

    def __format_text_uri_list(self):
        text_uri_list = g.get("text_uri_list", "").replace('"', "").replace("'", "")
        if text_uri_list:
            upload_mediafile_job_id = init_job(
                name="Upload Mediafiles",
                job_type="Mediafile upload",
                user_email=(get_user_context().email or "developers@inuits.eu"),
                get_rabbit=get_rabbit,
                track_async_children=True,
                parent_id=self.job_id,
            )
            # NOTE: This is techinically not a "parent job id", but this value
            # is used by the frontend to fill in the parent_job_id of the
            # mediafile upload links, which should be under the
            # upload_mediafile_job_id.
            if not self.parent_job_id:
                self.parent_job_id = upload_mediafile_job_id
            # NOTE: This technically means if the batch is ran, but then the
            # upload isn't started this job will stay in running
            start_job(upload_mediafile_job_id, get_rabbit=get_rabbit)
            uri_list = text_uri_list.split("\n")
            return [
                uri + f"&parent_job_id={upload_mediafile_job_id}"
                for uri in uri_list
                if uri
            ]
        return []

    def __set_request(self, method):
        request.method = method
        request.path = "/batch"
