from configuration import get_object_configuration_mapper
from flask import g, request
from inuits_policy_based_auth import RequestContext
from policy_factory import authenticate
from resources.generic_object import GenericObjectDetailV2
from util import encode_content_type_header


### DO NOT EDIT THIS FILE AND DO NOT USE DIRECTLY ###
### contact @eray for more info or feature/bug reports; refs #146921 ###
class Document(GenericObjectDetailV2):
    def get(self, *, id, spec):
        self.__set_request(id, "GET")
        return super().get(collection=None, id=id, spec=spec)

    def put(self, *, id, spec):
        self.__set_request(id, "PUT")
        g.enable_parsers = True
        return super().put(
            collection=None, id=id, spec=spec, content=g.get("content", {})
        )

    @authenticate(RequestContext(request))
    def patch(self, *, id, spec):
        self.__set_request(id, "PATCH")
        g.enable_parsers = True
        content_type = encode_content_type_header(request.content_type)
        if content_type != "applicationjson":
            default_config = get_object_configuration_mapper().get("_default")
            serialize = default_config.serialization(
                content_type, default_config.SCHEMA_TYPE
            )
            document = self._check_if_collection_and_item_exists(None, id)
            g.content = serialize(request.get_data(), document_type=document["type"])
        return super().patch(
            collection=None, id=id, spec=spec, content=g.get("content", {})
        )

    def delete(self, *, id, spec):
        self.__set_request(id, "DELETE")
        return super().delete(collection=None, id=id, spec=spec)

    def __set_request(self, id, method):
        request.method = method
        request.path = f"/entities/{id}"
        request.view_args = {**(request.view_args or {}), "id": id}
