from urllib.parse import parse_qs

from configuration import get_features, get_object_configuration_mapper
from elody.job import add_document_to_job, fail_job, finish_job, init_job, start_job
from elody.policies.helpers import get_flat_item_and_object_lists
from flask import g, request
from inuits_policy_based_auth import RequestContext
from policy_factory import authenticate, get_user_context
from rabbit import get_rabbit
from resources.base.document import Document
from resources.generic_object import GenericObjectV2
from werkzeug.datastructures import ImmutableMultiDict
from werkzeug.exceptions import BadRequest, Forbidden, MethodNotAllowed, NotAcceptable


### DO NOT EDIT THIS FILE AND DO NOT USE DIRECTLY ###
### contact @eray for more info or feature/bug reports; refs #146921 ###
class Documents(GenericObjectV2):
    @authenticate(RequestContext(request))
    def get(self, *, spec, collection="", is_type_required=False):
        if "export" not in get_features().get("bulk_operations", {}).keys():
            for accept_header in request.headers.get("Accept", "*/*").split(","):
                if accept_header.strip() in ["*/*", "application/json"]:
                    break
            else:
                raise NotAcceptable()

        self.__set_request("GET")
        g.enable_parsers = True
        if not request.args.get("type") and (
            id := request.args.get("ids", "").split(",")[0]
        ):
            try:
                document = self._check_if_collection_and_item_exists(None, id)
                request.args = ImmutableMultiDict(
                    {**request.args, "type": document["type"]}  # pyright: ignore
                )
            except:
                pass
        return super().get(
            collection=collection, spec=spec, is_type_required=is_type_required
        )

    def post(self, *, spec, is_content_prepared_for_creation=False, enable_jobs=True):
        self.__set_request("POST")
        g.enable_parsers = True
        content = g.get("content") or request.get_json() or {}
        if not is_content_prepared_for_creation:
            prepare_creation = (
                get_object_configuration_mapper()
                .get(content.get("type"))
                .crud()["creation_preparer"]
            )
            content = prepare_creation(content)
        contents = content
        if not isinstance(contents, list):
            contents = [contents]
        try:
            response = None
            for content in contents:
                g.content = content
                try:
                    response = super().post(
                        collection=None, content=g.get("content", {}), spec=spec
                    )
                except Forbidden as exception:
                    config = get_object_configuration_mapper().get(content.get("type"))
                    construct_document_exception_message = config.crud()[
                        "document_exception_message_constructor"
                    ]
                    message = construct_document_exception_message(
                        exception, str(exception.description)
                    )
                    raise BadRequest(
                        message
                    )  # temporary BadRequest until error codes are reworked
                if enable_jobs and (
                    current_job_id := (
                        request.args.get("current_job_id") or g.get("current_job_id")
                    )
                ):
                    if isinstance(response, dict):
                        add_document_to_job(
                            current_job_id,
                            response.get("_id"),
                            get_rabbit=get_rabbit,
                        )
                    else:
                        if request.headers.get("Accept", "").startswith("text/"):
                            if isinstance(response, str):
                                queries = parse_qs(
                                    response.split("?")[-1],
                                )
                                id = queries.get("id")
                                if isinstance(id, list):
                                    id = id[0]
                                add_document_to_job(
                                    current_job_id,
                                    id,
                                    get_rabbit=get_rabbit,
                                )
            return response
        except BadRequest as exception:
            return {"message": exception.description}, 400

    def put(self, *, spec):
        from resources.base.batch import Batch

        self.__set_request("PUT")
        return Batch().post(spec=spec, force_patch_only=True)

    @authenticate(RequestContext(request))
    def delete(self, *, spec):
        identifiers = request.get_json()["identifiers"]
        if (
            "delete" not in get_features().get("bulk_operations", {}).keys()
            and len(identifiers) > 1
        ):
            raise MethodNotAllowed()

        self.__set_request("DELETE")
        job_id = init_job(
            "Bulk delete",
            "Bulk delete",
            get_rabbit=get_rabbit,
            user_email=get_user_context().email,
            track_async_children=True,
        )
        start_job(job_id, get_rabbit=get_rabbit)

        document_resource = Document()
        for id in identifiers:
            document = self._check_if_collection_and_item_exists(None, id)
            flat_document, _ = get_flat_item_and_object_lists(document)
            title = flat_document.get(
                "metadata.title.value", flat_document.get("metadata.name.value")
            )
            child_job_id = init_job(
                f"Delete {document['type']}{f' \"{title}\"' if title else ''} | {flat_document.get('metadata.external_identifier.value', id)}",
                "Delete item",
                get_rabbit=get_rabbit,
                user_email=get_user_context().email,
                parent_id=job_id,
                track_async_children=True,
            )
            start_job(child_job_id, get_rabbit=get_rabbit)
            try:
                document_resource.delete(id=id, spec=spec)
                finish_job(child_job_id, get_rabbit=get_rabbit)
            except Exception as exception:
                fail_job(child_job_id, str(exception), get_rabbit=get_rabbit)

        finish_job(job_id, get_rabbit=get_rabbit)
        return self._create_response_according_accept_header({"parent_job_id": job_id})

    def __set_request(self, method):
        request.method = method
        request.path = "/entities"
        request.view_args = request.view_args or {}
        request.view_args.pop("id", None)
