from flask import g, request
from inuits_policy_based_auth import RequestContext
from policy_factory import authenticate
from policy_factory import get_user_context
from resources.filter import FilterGenericObjectsV2


### DO NOT EDIT THIS FILE AND DO NOT USE DIRECTLY ###
### contact @eray for more info or feature/bug reports; refs #146921 ###
class Filter(FilterGenericObjectsV2):
    @authenticate(RequestContext(request))
    def post(self, spec, is_type_required=False):
        self.__set_request("POST")
        resolve_collections = get_user_context().bag["collection_resolver"]
        g.content = g.get("content") or request.get_json()
        filters = []
        for filter in g.get("content", []):
            if filter.get("lookup") and not filter["lookup"].get("from"):
                collection = resolve_collections(id=filter["value"])[0]
                filter["lookup"]["from"] = collection
            filters.append(filter)
        return super().post(
            collection=None,
            content=filters,
            spec=spec,
            is_type_required=is_type_required,
        )

    def __set_request(self, method):
        request.method = method
        request.path = "/entities/filter"
